### ISSUE TITLE
Wifi disconnect causes Fatal exception 28 (LoadProhibitedCause)

### ISSUE THREAD

**Issue by quantumlicht** [Links2004/arduinoWebSockets#138] opened 2016-11-11 03:18 UTC
I am kind of stumped. I've been running your library successfully for a while (thanks for the great job by the way!) on an ESP8266 olimex with no issues.

2 days ago I got back to my project, and the behavior is now different. Here's a stack trace I captured from Debug port on `Serial` with the debug level set to `core + wifi`

The socket disconnects and then crashes. 
```
wifi evt: 7
wifi evt: 7
[hostByName] request IP for: remindr-ws.herokuapp.com
[hostByName] Host: remindr-ws.herokuapp.com IP: 184.72.235.40
:ref 1
:wr
:sent 344
:ww
:rn 124
:rcl
:abort
:c0 1, 124
:ur 1
:del
[WSc] Disconnected!
Fatal exception 28(LoadProhibitedCause):
epc1=0x40206fd4, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000

Exception (28):
epc1=0x40206fd4 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: cont 
sp: 3fff1c90 end: 3fff1ed0 offset: 01a0

>>>stack>>>
3fff1e30:  3fff0b58 3fff1e80 3fff0b78 40206f94  
3fff1e40:  0000000a 3fff3aec 0000000a 40204bf2  
3fff1e50:  3ffe000d 3fff0ea0 3fff3aec 402077fb  
3fff1e60:  00000000 00000050 3fff1e80 4020788f  
3fff1e70:  3fffdad0 3fff0b78 3fff0b58 40207030  
3fff1e80:  3fff39a4 0000000f 00000000 402086c0  
3fff1e90:  3fffdad0 00000001 3fff0b58 40207165  
3fff1ea0:  3fffdad0 00000000 3fff0e99 402036d7  
3fff1eb0:  3fffdad0 00000000 3fff0e99 40208124  
3fff1ec0:  feefeffe feefeffe 3fff0eb0 40100970  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(1,6)


 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset
```

I have very little experience troubleshooting stack dump like this. I am willing to give out more information if need be. Don't hesitate to ask if you need anything.

**Comment by Links2004** [comment] 2016-11-11 18:58
hi,
you can map the memory addresses from the trace with:
https://github.com/me-no-dev/EspExceptionDecoder

simple upload you sketch, wait for a stack trace and copy it to the tool.
then you get the functions names and eave the line in the code where the error happens.
with this info's and the code you use we can check whats the problem is.

some first hint gives ```LoadProhibitedCause``` and ```depc=0x00000000``` its may a null ptr usage.

may enable the the debug output of the websockets too.
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSockets.h#L30
by this we can see what data is processed by the code.

**Comment by quantumlicht** [comment] 2016-11-16 01:54
Thanks for telling me about this util ESPExceptionDecoder!  I went ahead and fiddled with my local copy of the library.
It seems like there is a code path that generates duplicate headers. It happens in the case that you are not a socketIO client. These headers are getting set twice:
```
"Host: " + _host + ":" + _port + "\r\n"
"Origin: file://\r\n"
"User-Agent: arduino-WebSocket-Client\r\n";
```
Commenting out this code seems to solve the issue.
https://github.com/Links2004/arduinoWebSockets/blame/master/src/WebSocketsClient.cpp#L450

However, I don't understand why it used to work and not it doesnt. I did not upgrade my websocket server library recently.


Would you like a PR that addresses this issue or you prefer doing it yourself? Or perhaps is there a good reason for duplucating the headers?

Regards

**Comment by quantumlicht** [comment] 2016-11-16 01:56
As part of the fix, I'd also add a debug log to output the headers, I think it's important for debugging. This allowed me to see the problem

**Comment by Links2004** [comment] 2016-11-16 17:18
yes, there are some duplicate headers.
feel free to create a PR for it.

I think the best is to remove them from here:
https://github.com/Links2004/arduinoWebSockets/blob/master/src/WebSocketsClient.cpp#L428-L435
since they are needed in both cases but duplication is not necessary.

**Comment by quantumlicht** [comment] 2016-11-17 01:26
https://github.com/Links2004/arduinoWebSockets/pull/143

**Comment by Links2004** [comment] 2016-11-17 16:48
merged

**Closed** 2016-11-18 19:47 UTC

**Comment by felangga** [comment] 2017-05-25 15:11
Still had this problem 

```
Fatal exception 28(LoadProhibitedCause):
epc1=0x402335e4, epc2=0x00000000, epc3=0x00000000, excvaddr=0x1a01a8d8, depc=0x00000000

Exception (28):
epc1=0x402335e4 epc2=0x00000000 epc3=0x00000000 excvaddr=0x1a01a8d8 depc=0x00000000

ctx: sys 
sp: 3ffffd70 end: 3fffffb0 offset: 01a0

>>>stack>>>
3fffff10:  402108f5 00000000 00000000 3ffec99d  
3fffff20:  00000002 ffffffff 5e4cffff 3ffef2c0  
3fffff30:  000005e0 00000000 40103949 3fff1fbc  
3fffff40:  3ffecf5a 3ffecf70 3fff4674 4023377c  
3fffff50:  0101a8c0 1a01a8c0 40104a72 3ffee890  
3fffff60:  3ffecf76 3ffecf80 3fff1fc0 00000002  
3fffff70:  00000000 401011ab 00000000 00000000  
3fffff80:  40209e26 3fffdab0 00000002 3fff204c  
3fffff90:  3fffdc80 00000000 3fff4674 4021deef  
3fffffa0:  40000f49 3fffdab0 3fffdab0 40000f49  
<<<stack<<<
@f�8�@�����
```

**Comment by Links2004** [comment] 2017-05-25 19:07
please decode the stack dump with:
https://github.com/me-no-dev/EspExceptionDecoder
the addresses are individual for you build / code,
with them alone its impossible to get an Idea whats going on.
